# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  postgresdb:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
  server:
    depends_on:
      - postgresdb
    # restart: unless-stopped
    env_file: ./.env
    build:
      context: .
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      NODE_ENV: production
      DISCORD_TOKEN: 
      CLIENT_ID: 
      GUILD_ID: 
      GENERAL_CHANNEL_ID: 
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: jop
      DB_PORT: 5432
    stdin_open: true
    tty: true

volumes:
  db:

      


